[project]
name = "3dprint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michal Pech", email = "michal.pech@radalytica.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
3dprint = "3dprint:main"

[build-system]
requires = ["uv_build>=0.11.19,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
